name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    container:
      image: cypress/included:13.15.0

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: Check Formatting
        run: npm run format:check

      - name: Lint
        run: npm run lint

      - name: Unit Tests
        run: npm test

      - name: Build Project
        run: npm run build

      - name: Run Cypress Tests
        run: npx cypress run
